### PR TITLE
Ensuring multi-line transforms are tracked

### LINKED ISSUE #117: postcss-lit Breaks Transforms in Multiline Statements
As shown in [stevematney/postcss-lit-nesting-break:main](https://github.com/stevematney/postcss-lit-nesting-break), nested selectors which contain newlines end up removing transforms in the `stringify` process, resulting in incorrect output. In the case of a nested selector with newlines, the output from postcss-lit will cause a rollback of selector transformation from `postcss-nested`.  This results in output like the diff below, where the red `-` lines show the current output, and the green `+` lines show the expected output.

```diff
--- broken.js	2026-02-10 11:24:06.592052000 -0700
+++ corrected.js	2026-02-10 11:23:18.447638700 -0700
@@ -5,10 +5,10 @@
     cursor: wait;
   }

-    .start,
-    .label,
-    .end,
-    .caret {
+    .loading .start,
+    .loading .label,
+    .loading .end,
+    .loading .caret {
       visibility: hidden;
     }
```

### PR DESCRIPTION
**Pull request by stevematney**
Fixes #117

### CODE REVIEW

File: src/proxyNode.ts [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+        set(value) {
+          node.raws[proxiedProp] = value;
+          correctNodeLocation(node);
+        }
+      };
+      return descriptors;
+    },
+    {} as Record<string, PropertyDescriptor>
+  );
+  Object.defineProperties(node, propDescriptors);
```
Comment (stevematney) [inline src/proxyNode.ts]: Note: a true `Proxy` could not be used here, as it caused conflicts with PostCSS's internal proxying behavior.

**Review by stevematney — COMMENTED** [review]
This seems better to me! There's some duplication that could potentially be somewhat reduced, but that's probably not necessary unless we think future iterations could become difficult in terms of change and maintenance because of it. Removing the duplication would also depend on before and after lines being calculated in the same way forever, which may or may not be true.

**Comment by stevematney** [comment]
> presumably you mean this repeated logic of splitting lines to count them, then correcting the string?
> 
> we could possibly unify that into some more generic function but i'd probably do it in a follow up

Yep! That's what I was looking at, but I'm always hesitant to say that perceived duplication _should be removed_, because sometimes it looks like replicated logic in practice, but is actually logic with different underlying purposes. Also, I don't think it's that big of a deal in this case.

Thanks for tackling this and putting in so much work on it!
